name: Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup msys2
        if: matrix.os == 'windows-2022'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            zip
            msys2-devel
            zlib-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-i686-toolchain
            mingw-w64-x86_64-openssl
            mingw-w64-i686-openssl
            openssl-devel

      - name: Install requirements
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt install libssl-dev

      - name: Build git-crypt
        if: matrix.os == 'windows-2022'
        shell: msys2 {0}
        run: make LDFLAGS="-static-libstdc++ -static -lcrypto -lws2_32"

      - name: Build git-crypt
        if: matrix.os == 'ubuntu-20.04'
        run: make LDFLAGS="-lcrypto"

      - name: zip artifacts
        if: matrix.os == 'windows-2022'
        shell: msys2 {0}
        run: |
          zip --junk-paths -r git-crypt-windows.zip git-crypt.exe

      - name: zip artifacts
        if: matrix.os == 'ubuntu-20.04'
        run: |
          zip --junk-paths -r git-crypt-linux.zip git-crypt

      - name: Upload Release Asset
        if: contains(github.ref, 'refs/tags/') && matrix.os == 'windows-2022'
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./git-crypt-windows.zip
          asset_name: git-crypt-windows.zip

      - name: Upload Release Asset
        if: contains(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-20.04'
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./git-crypt-linux.zip
          asset_name: git-crypt-linux.zip
