name: Build

on:
  release:
    types: [published]

jobs:
  check-tag:
    name: Get the release version only if the tag matches "major.minor.patch"
    runs-on: ubuntu-20.04
    outputs:
      release_version: ${{ steps.check-tag.outputs.release_version }}
    steps:
      - name: check tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ "${{ github.ref }}" =~ refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=release_version::$(echo ${{ github.ref }} | sed -E 's/refs\/tags\/(.*)/\1/' )"
          fi

  build:
    name: Build release
    # The `needs` and `if` are used to make sure that `check-tag` has completed and the `release_version` is set
    needs: check-tag
    if: needs.check-tag.outputs.release_version != ''
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup msys2
        if: matrix.os == 'windows-2022'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            git
            zip
            msys2-devel
            zlib-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-i686-toolchain
            mingw-w64-x86_64-openssl
            mingw-w64-i686-openssl
            openssl-devel

      - name: Install requirements
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt install libssl-dev

      - name: Build git-crypt
        if: matrix.os == 'windows-2022'
        shell: msys2 {0}
        run: make LDFLAGS="-static-libstdc++ -static -lcrypto -lws2_32"

      - name: Build git-crypt
        if: matrix.os == 'ubuntu-20.04'
        run: make LDFLAGS="-lcrypto"

      - name: zip artifacts
        if: matrix.os == 'windows-2022'
        shell: msys2 {0}
        run: |
          zip --junk-paths -r git-crypt-windows.zip git-crypt.exe

      - name: zip artifacts
        if: matrix.os == 'ubuntu-20.04'
        run: |
          zip --junk-paths -r git-crypt-linux.zip git-crypt

      - name: Upload Release Asset
        if: contains(github.ref, 'refs/tags/') && matrix.os == 'windows-2022'
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./git-crypt-windows.zip
          asset_name: git-crypt-windows-v${{ needs.check-tag.outputs.release_version }}.zip

      - name: Upload Release Asset
        if: contains(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-20.04'
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./git-crypt-linux.zip
          asset_name: git-crypt-linux-v${{ needs.check-tag.outputs.release_version }}.zip
